spring:
  application:
    name: streaming-service

  data:
    redis:
      host: localhost
      port: 6379

  kafka :
    bootstrap-servers: localhost:9092
    group-id: Streaming-service-group
    auto-offset-reset: earliest
    key-deserializer: org apache.kafka.common.serilization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: "*"
          use:
            type:
              headers: false

          value:
            default:
              type: com.watchora.streamingservice.Service.VideoEncodedEvent

server:
  port: 8084

#Aws configration

aws:
  access-key:
    ${AWS_ACCESS_KEY: }

  secret-key:
    ${AWS_SECRET_KEY: }

  region:
    ${AWS_REGION: }

  S3:
    bucket-name:
    ${AWS_BUCKET_NAME: }

    presigned-url-expiry : 68

management:
  endpoints:
    web:
      exposure:
        include: health, info

